test:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes_from:
    - cache
  mem_limit: 400m

builder:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes_from:
    - cache
  command: ["activator", "clean", "stage"]

cache:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes:
    - /tmp/cache:/root
  entrypoint: "true"
